version: '3.4'

services:
  bistro.webapi:
    container_name: bistrowebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5100
    ports:
      - "5100:5100"
    expose:
      - "5100"
    networks:
      - bistro-network

  bistro.webapp:
    container_name: bistrowebapp
    environment:
      - "BistroApiUrl=http://bistro.webapi:5100"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5101
    depends_on:
      - bistro.webapi
    ports:
      - "5101:5101"
    networks:
      - bistro-network