version: '3.4'

services:
  bistro.webapi:
    image: ${DOCKER_REGISTRY-}bistrowebapi
    build:
      context: .
      dockerfile: src/Bistro.WebApi/Dockerfile
  bistro.webapp:
    image: ${DOCKER_REGISTRY-}bistrowebapp
    build:
      context: .
      dockerfile: src/Bistro.WebApp/Dockerfile

networks:
  bistro-network:
    external: true